### ISSUE TITLE
Domande sul programma

### ISSUE THREAD

**Issue by chiaralansia** [TdP-prove-finali/LanzaChiara#1]
Buona sera professore,
poiché la prima volta che ho fatto il commit in realtà avevo solo caricato i file e non erano collegati con il mio progetto, ora mi ritrovo due cartelle, come posso cancellare quella scollegata?

I controlli li sto facendo scrivendo esplicitamente le categorie perché ogni categoria indicata ha dei vincoli particolari, è un problema il fatto che sia così specifico e poco generale?

Avrei anche bisogno di un aiuto con la ricorsione, ci sono pochi vincoli e per questo non arriva ad una conclusione o sbaglio qualcos'altro? Con il debug mi crea le candidate ma non riesco ad andare fino in fondo per capire dov'è il problema in quanto i prodotti sono tanti..

**Comment by fulcorno** [comment]
1) per cancellare qualcosa occorre fare un clone completo del repository (probabilmente ce l'hai già in Eclipse), poi cancellare (sul tuo PC) la cartella, e fare commit/push della cancellazione). Se hai problemi, dimmelo e lo posso fare io. (in generale sempre meglio evitare la funzionalità di upload).

2) non si riescono ad organizzare tutti i controlli in una struttura ordinata? ad esempio riesci ad esprimerli sotto forma di tabella? sotto forma di una serie di regole? (se c'è X deve esserci Y, ma non può esserci Z)
Se riuscissi a "formalizzare" queste regole, poi le si potrebbero codificare in una mappa, o in un grafo, ed il tuo programma si potrebbe limitare ad "interpretare" le regole. Prova a descriverle nel modo più ordinato possibile, poi guardiamo insieme come conviene codificarle.
Se poi non fosse possibile, ovviamente si possono codificare in Java, ma si rischia di avere codice poco gestibile...

3) in fase di sviluppo e debug conviene provare innanzitutto con POCHI prodotti e POCHE alternative. Quando poi funziona (e si è debuggato "nel piccolo", si possono aggiungere gradualmente ulteriori dati.

4) per domande così diverse sarebbe bene lavorare con messaggi/issue diversi, altrimenti la conversazione diventa un casino...

**Comment by chiaralansia** [comment]
La ringrazio professore,
1: risolto
2:Quando è disponibile per una consulenza per vedere come codificarle? 
3: ho creato un dataset ridotto per gestire meglio il debug
